language: php

php:
    - 7.0
    - 7.1.18
    - 7.2
    - 7.3

services:
    - mysql

install:
    # Install wireshell
    - composer global require wireshell/wireshell

    # Install ProcessWire
    - cd ../..
    - ~/.config/composer/vendor/bin/wireshell new processwire --profile=blank --dbUser=root --dbPass= --dbName=processwire --timezone=Europe/Berlin --httpHosts=localhost --username=admin --userpass=s3cr3t --useremail=john.doe@foo.com

    # Symlink the cloned module to site/modules
    - cd processwire
    - ln -s $TRAVIS_BUILD_DIR site/modules/TemplateEngineFactory

    # Install dependencies
    - cd site/modules/TemplateEngineFactory
    - composer install

script:
    - vendor/bin/phpunit --bootstrap tests/bootstrap.php tests --colors
